### ISSUE TITLE
请问一下作者，此UI库是否可以以TSX的语法进行开发

### ISSUE THREAD

**Issue by guozhongjia001** [haoziqaq/varlet#199]
# About `docs`
如果可以的话，想问下作者，我使用指令赋值该怎么去操作呢，比如这个水波指令去设置颜色是不会生效的。
![Uploading image.png…]()

**Comment by haoziqaq** [comment]
vue3有专门针对指令的tsx语法，你可以去官方看看。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月17日(周三) 中午1:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [haoziqaq/varlet] 请问一下作者，此UI库是否可以以TSX的语法进行开发 (Issue #199)




 
About docs
 
如果可以的话，想问下作者，我使用指令赋值该怎么去操作呢，比如这个水波指令去设置颜色是不会生效的。
 
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guozhongjia001** [comment]
好的，谢谢
