### ISSUE TITLE
varlet/cli 用于 pc 端组件库创建是否开箱即用？

### ISSUE THREAD

**Issue by wll8** [haoziqaq/varlet#207]
从给出的截图上看起来在右边会出现一个类似移动端的预览视图。所以我在想，如果是开发 pc 端的组件，例如一个分页器，这时候使用移动端模式预览肯定是不太行的。

那么如果要支持 pc 端，是不是简单修改一下这个视图大小就行就了？还是说这个 cli 有很多代码是基于移动端进行考虑的？

![image](https://user-images.githubusercontent.com/28223260/143813993-b8970645-2f2d-4ae1-b6ec-9b19f635f504.png)

**Comment by haoziqaq** [comment]
对的 pc也是开箱即用的 配置有个选项关闭之后 右侧的手机预览就不见了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月29日(周一) 中午1:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [haoziqaq/varlet] varlet/cli 用于 pc 端组件库创建是否开箱即用？ (Issue #207)




 
从给出的截图上看起来在右边会出现一个类似移动端的预览视图。所以我在想，如果是开发 pc 端的组件，例如一个分页器，这时候使用移动端模式预览肯定是不太行的。
 
那么如果要支持 pc 端，是不是简单修改一下这个视图大小就行就了？还是说这个 cli 有很多代码是基于移动端进行考虑的？
 

 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by haoziqaq** [comment]
本身varlet是针对移动设备(并不局限于小屏手机，包括桌面，平板，等很多触控设备)，所以宽屏幕是在考虑范围之内的。
