### ISSUE TITLE
想问下@varlet/cli暗黑模式的问题

### ISSUE THREAD

**Issue by z851103999** [haoziqaq/varlet#208]
# About `styles` 🛠️

## 如何根据暗黑模式值来进行判断，我看到自带配置的一些默认和暗黑属性的值，我如何在我组件判断或者引入这些值？我能否在配置文件增加更多暗黑模式属性。

**Comment by haoziqaq** [comment]
正常情况下组件库的暗黑模式主题和文档是解耦的，不使用同一套主题。配置中的主题变量会注入到文档站点里，你也可以自定义一些变量提供给你的组件example使用，这是可以的

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月29日(周一) 晚上6:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [haoziqaq/varlet] ***@***.***/cli暗黑模式的问题 (Issue #208)




 
About styles 🛠️
 
如何根据暗黑模式值来进行判断，我看到自带配置的一些默认和暗黑属性的值，我如何在我组件判断或者引入这些值？我能否在配置文件增加更多暗黑模式属性。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by haoziqaq** [comment]
文档的主题变量的使用方式是以--site-config+变量名访问的 你也可以在body里看见



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月29日(周一) 晚上6:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [haoziqaq/varlet] ***@***.***/cli暗黑模式的问题 (Issue #208)




 
About styles 🛠️
 
如何根据暗黑模式值来进行判断，我看到自带配置的一些默认和暗黑属性的值，我如何在我组件判断或者引入这些值？我能否在配置文件增加更多暗黑模式属性。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by z851103999** [comment]
好的谢谢
